plugins:
  preset-lint-consistent:
  preset-lint-markdown-style-guide:
  preset-lint-recommended:
  validate-links:
  # Customized settings
  lint-list-item-indent: mixed
  lint-maximum-line-length: 128
  lint-no-undefined-references: false
  lint-no-shortcut-reference-link: false
  lint-no-duplicate-headings: false