NAME: PwSh.Fw.Core
VERSION: 
AUTHORS: 
- Charles-Antoine Degennes
OWNER: Charles-Antoine Degennes
LICENSEURL: https://gitlab.com/pwsh.fw/pwsh.fw.core/raw/master/LICENSE
URL: https://gitlab.com/pwsh.fw/pwsh.fw.core
ICONURL: https://gitlab.com/pwsh.fw/pwsh.fw.core/raw/master/images/favicon.png
DESCRIPTION: Root module of a simple Powershell Framework. It is specialized in writing system scripts, but it can of course do more.
TAGS:
- PSEdition_Core
- Windows
- Linux
- MacOS
- PwSh.Fw
- core
RELEASENOTES: null
COPYRIGHT: (c) 2020 Charles-Antoine Degennes. All rights reserved.